version: '3'
services:
  php:
    build: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - './:/var/www/symfony:cached'
  nginx:
    build: ./docker/nginx
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/symfony:cached'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "9906:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql