index:
    path: /
    controller: App\Controller\DefaultController::index
calculate:
    path: /packing/calculation
    controller: App\Controller\PackingCalculationController::calc
    methods: [POST]
